### ISSUE TITLE
Add tests for the units

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#33]
We should / could add some tests on the units. We focus on pint and UDUNITS2. Pint testing should be strait forward (i.e. trying to parse all units without any errors), but for UDUNITS2 there seems to be few candidates:
* python: cf-xarray (see #26, [comment from @dcherian](https://github.com/DocOtak/gsw-xarray/issues/26#issuecomment-1051363746_)
* compiled: [UDUNITS-2](https://www.unidata.ucar.edu/software/udunits/udunits-2.0.4/)
* python: [cf-units](https://github.com/SciTools/cf-units)
* other?

I haven't tested any of these solutions, what matters is having a parsing solution (forced to be restricted to UDUNITS2), so we should dig in the docs and try to see which library to use.

**Comment by rcaneill** [comment]
@dcherian is it possible to test only UDUNITS2 compatibility of units with cf_xarray.units? (like parsing using UDUNITS2 rules, but not pint rules)

**Comment by dcherian** [comment]
I don't understand. cf-xarray teaches pint how to interpret UDUNITS strings so that we can call `da.pint.quantify` without errors.

Are you asking about actually validating the units string as a  valid UDUNITS string? If so, cf-xarray does not do that.

Maybe one of the compliance checkers (https://github.com/ioos/compliance-checker) does that?

**Comment by rcaneill** [comment]
> Are you asking about actually validating the units string as a valid UDUNITS string? If so, cf-xarray does not do that.

Yes that was my question. I have never used pint so I feel quite lost... Thanks for the answer!
